filter:
    paths:
        - 'src/*'
before_commands:
    - 'composer self-update'
    - 'composer install -n --prefer-source'
tools:
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR1
    php_code_coverage:
        test_command: phpunit